# World Development Indicators data set

The goal of this notebook is to investigate influential outliers in the WDI data set.

In [1]:
import shap

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

import seaborn as sns
import matplotlib.pyplot as plt
from catboost import CatBoostRegressor

In [2]:
from main_iom import *

In [3]:
sns.set_theme(style='white')

We read in the data and select a few variables. Our goal is to predict the GDP in 2022 of a country given captial, savings, population growth and consumption.

In [4]:
df = pd.read_csv("WDICSV.csv")
df = df[["Country Name", "Country Code", "Indicator Name", "Indicator Code", "2022"]]

In [5]:
df_final = df[df["Indicator Name"].isin(["GDP per capita (current US$)", 
                                         "Gross capital formation (current US$)", 
                                         "Population growth (annual %)", 
                                         "Gross savings (current US$)", 
                                         "Final consumption expenditure (current US$)"])] \
                                    .pivot(columns='Indicator Name', 
                                           index='Country Name', 
                                           values='2022') \
                                    .dropna()

In [6]:
df_final.columns.name= None
df_final.index.name = None

We set up the data to be used in the model

In [7]:
X = df_final.drop("GDP per capita (current US$)", axis=1)
y = df_final['GDP per capita (current US$)']

We set up a randomized grid search fro hyperparameter tuning.

In [8]:
grid = {'learning_rate': [0.03, 0.1],
        'depth': [4, 6, 10],
        'l2_leaf_reg': [1, 3, 5, 7, 9]}

In [9]:
mod = CatBoostRegressor(random_seed=123)

result = mod.randomized_search(grid, X=X, y=y, n_iter=10)

0:	learn: 31383.8874624	test: 27471.5803819	best: 27471.5803819 (0)	total: 133ms	remaining: 2m 12s
1:	learn: 30903.0483510	test: 27244.4746903	best: 27244.4746903 (1)	total: 134ms	remaining: 1m 6s
2:	learn: 30412.9742965	test: 27042.1942270	best: 27042.1942270 (2)	total: 135ms	remaining: 44.8s
3:	learn: 29947.3514475	test: 26838.4170843	best: 26838.4170843 (3)	total: 136ms	remaining: 33.7s
4:	learn: 29511.9030865	test: 26635.6146715	best: 26635.6146715 (4)	total: 136ms	remaining: 27.1s
5:	learn: 29141.9429118	test: 26494.3993695	best: 26494.3993695 (5)	total: 137ms	remaining: 22.7s
6:	learn: 28684.9280290	test: 26336.8161747	best: 26336.8161747 (6)	total: 137ms	remaining: 19.5s
7:	learn: 28306.4197211	test: 26168.0753282	best: 26168.0753282 (7)	total: 138ms	remaining: 17.1s
8:	learn: 27934.7978331	test: 26026.7287331	best: 26026.7287331 (8)	total: 139ms	remaining: 15.3s
9:	learn: 27572.2164484	test: 25874.3361701	best: 25874.3361701 (9)	total: 140ms	remaining: 13.8s
10:	learn: 27206.0184608	test: 25713.8740288	best: 25713.8740288 (10)	total: 140ms	remaining: 12.6s
11:	learn: 26849.1650818	test: 25566.0090249	best: 25566.0090249 (11)	total: 141ms	remaining: 11.6s
12:	learn: 26512.5211853	test: 25437.1997912	best: 25437.1997912 (12)	total: 142ms	remaining: 10.8s
13:	learn: 26226.7176915	test: 25313.0699586	best: 25313.0699586 (13)	total: 142ms	remaining: 10s
14:	learn: 25943.8968482	test: 25204.8995019	best: 25204.8995019 (14)	total: 143ms	remaining: 9.39s
15:	learn: 25655.9314920	test: 25106.8056203	best: 25106.8056203 (15)	total: 144ms	remaining: 8.84s
16:	learn: 25349.4123238	test: 25037.7258938	best: 25037.7258938 (16)	total: 144ms	remaining: 8.36s
17:	learn: 25060.6725467	test: 24991.6721735	best: 24991.6721735 (17)	total: 145ms	remaining: 7.92s
18:	learn: 24801.5960349	test: 24930.0559769	best: 24930.0559769 (18)	total: 146ms	remaining: 7.54s
19:	learn: 24536.9064804	test: 24871.9779288	best: 24871.9779288 (19)	total: 147ms	remaining: 7.19s
20:	learn: 24310.3381868	test: 24816.8339595	best: 24816.8339595 (20)	total: 147ms	remaining: 6.87s
21:	learn: 24123.9518457	test: 24769.4951088	best: 24769.4951088 (21)	total: 148ms	remaining: 6.58s
22:	learn: 23902.8875397	test: 24766.7106930	best: 24766.7106930 (22)	total: 149ms	remaining: 6.32s
23:	learn: 23688.1888505	test: 24715.2344453	best: 24715.2344453 (23)	total: 149ms	remaining: 6.08s
24:	learn: 23496.4274425	test: 24667.6600079	best: 24667.6600079 (24)	total: 150ms	remaining: 5.85s
25:	learn: 23290.2046975	test: 24638.1451099	best: 24638.1451099 (25)	total: 151ms	remaining: 5.65s
26:	learn: 23100.8768767	test: 24614.3847112	best: 24614.3847112 (26)	total: 152ms	remaining: 5.46s
27:	learn: 22885.7371420	test: 24608.3393627	best: 24608.3393627 (27)	total: 152ms	remaining: 5.28s
28:	learn: 22688.9230725	test: 24588.0843956	best: 24588.0843956 (28)	total: 153ms	remaining: 5.12s
29:	learn: 22508.7837157	test: 24552.5282702	best: 24552.5282702 (29)	total: 154ms	remaining: 4.97s
30:	learn: 22316.0199591	test: 24528.8153389	best: 24528.8153389 (30)	total: 154ms	remaining: 4.82s
31:	learn: 22130.6695992	test: 24499.7278913	best: 24499.7278913 (31)	total: 155ms	remaining: 4.69s
32:	learn: 21991.0430130	test: 24470.0234114	best: 24470.0234114 (32)	total: 156ms	remaining: 4.56s
33:	learn: 21839.5992162	test: 24495.0501854	best: 24470.0234114 (32)	total: 156ms	remaining: 4.44s
34:	learn: 21644.5057036	test: 24492.2595621	best: 24470.0234114 (32)	total: 157ms	remaining: 4.33s
35:	learn: 21510.5239877	test: 24480.1802159	best: 24470.0234114 (32)	total: 158ms	remaining: 4.22s
36:	learn: 21367.3761747	test: 24491.2453969	best: 24470.0234114 (32)	total: 158ms	remaining: 4.12s
37:	learn: 21244.1340209	test: 24480.9156334	best: 24470.0234114 (32)	total: 159ms	remaining: 4.02s
38:	learn: 21080.0344232	test: 24503.7238490	best: 24470.0234114 (32)	total: 160ms	remaining: 3.94s
39:	learn: 20930.7544462	test: 24496.9113548	best: 24470.0234114 (32)	total: 160ms	remaining: 3.85s
40:	learn: 20816.5357625	test: 24511.1768050	best: 24470.0234114 (32)	total: 161ms	remaining: 3.76s
41:	learn: 20676.6733307	test: 24464.1071886	best: 24464.1071886 (41)	total: 162ms	remaining: 3.69s
42:	learn: 20514.9795652	test: 24454.2067934	best: 24454.2067934 (42)	total: 162ms	remaining: 3.62s
43:	learn: 20401.7931664	test: 24442.9174780	best: 24442.9174780 (43)	total: 163ms	remaining: 3.54s
44:	learn: 20307.7010703	test: 24449.2839639	best: 24442.9174780 (43)	total: 164ms	remaining: 3.48s
45:	learn: 20195.1295812	test: 24441.7119188	best: 24441.7119188 (45)	total: 165ms	remaining: 3.42s
46:	learn: 20074.3381044	test: 24446.0150422	best: 24441.7119188 (45)	total: 166ms	remaining: 3.36s
47:	learn: 19967.9483880	test: 24475.4460712	best: 24441.7119188 (45)	total: 166ms	remaining: 3.3s
48:	learn: 19834.2245111	test: 24520.6994741	best: 24441.7119188 (45)	total: 167ms	remaining: 3.24s
49:	learn: 19753.1507900	test: 24536.1537240	best: 24441.7119188 (45)	total: 167ms	remaining: 3.18s
50:	learn: 19632.9646895	test: 24535.4890794	best: 24441.7119188 (45)	total: 168ms	remaining: 3.13s
51:	learn: 19570.3247987	test: 24565.4077583	best: 24441.7119188 (45)	total: 169ms	remaining: 3.08s
52:	learn: 19471.9350882	test: 24569.8548154	best: 24441.7119188 (45)	total: 169ms	remaining: 3.02s
53:	learn: 19410.3376698	test: 24573.4608511	best: 24441.7119188 (45)	total: 170ms	remaining: 2.98s
54:	learn: 19331.4304201	test: 24570.2044389	best: 24441.7119188 (45)	total: 171ms	remaining: 2.94s
55:	learn: 19261.1316930	test: 24594.9937479	best: 24441.7119188 (45)	total: 172ms	remaining: 2.9s
56:	learn: 19159.8035434	test: 24598.4101093	best: 24441.7119188 (45)	total: 173ms	remaining: 2.86s
57:	learn: 19108.5041053	test: 24597.2826850	best: 24441.7119188 (45)	total: 174ms	remaining: 2.82s
58:	learn: 19040.6222208	test: 24605.7132732	best: 24441.7119188 (45)	total: 175ms	remaining: 2.79s
59:	learn: 18941.0697977	test: 24607.9808435	best: 24441.7119188 (45)	total: 176ms	remaining: 2.75s
60:	learn: 18869.0385931	test: 24618.8694894	best: 24441.7119188 (45)	total: 177ms	remaining: 2.72s
61:	learn: 18811.7160559	test: 24640.5303845	best: 24441.7119188 (45)	total: 178ms	remaining: 2.69s
62:	learn: 18732.3242980	test: 24666.7857038	best: 24441.7119188 (45)	total: 207ms	remaining: 3.08s
63:	learn: 18673.7306008	test: 24685.2483076	best: 24441.7119188 (45)	total: 227ms	remaining: 3.33s
64:	learn: 18560.9453370	test: 24705.3384963	best: 24441.7119188 (45)	total: 238ms	remaining: 3.42s
65:	learn: 18478.1401478	test: 24714.5983405	best: 24441.7119188 (45)	total: 259ms	remaining: 3.67s
66:	learn: 18424.3341429	test: 24717.4036443	best: 24441.7119188 (45)	total: 279ms	remaining: 3.89s
67:	learn: 18363.2797162	test: 24732.9746281	best: 24441.7119188 (45)	total: 291ms	remaining: 3.98s
68:	learn: 18314.5807041	test: 24760.7579255	best: 24441.7119188 (45)	total: 303ms	remaining: 4.08s
69:	learn: 18268.9182431	test: 24754.4150642	best: 24441.7119188 (45)	total: 313ms	remaining: 4.17s
70:	learn: 18206.6291750	test: 24780.6079334	best: 24441.7119188 (45)	total: 322ms	remaining: 4.21s
71:	learn: 18140.5646677	test: 24784.6050414	best: 24441.7119188 (45)	total: 331ms	remaining: 4.26s
72:	learn: 18070.8724890	test: 24803.2422023	best: 24441.7119188 (45)	total: 332ms	remaining: 4.21s
73:	learn: 18017.6170065	test: 24795.2011494	best: 24441.7119188 (45)	total: 333ms	remaining: 4.17s
74:	learn: 17961.2848684	test: 24826.6197813	best: 24441.7119188 (45)	total: 334ms	remaining: 4.12s
75:	learn: 17908.6536122	test: 24828.9165948	best: 24441.7119188 (45)	total: 335ms	remaining: 4.07s
76:	learn: 17834.8206122	test: 24876.6348632	best: 24441.7119188 (45)	total: 335ms	remaining: 4.02s
77:	learn: 17780.5556027	test: 24907.1780248	best: 24441.7119188 (45)	total: 336ms	remaining: 3.97s
78:	learn: 17720.4413378	test: 24936.4807784	best: 24441.7119188 (45)	total: 337ms	remaining: 3.93s
79:	learn: 17660.2876641	test: 24937.7670367	best: 24441.7119188 (45)	total: 338ms	remaining: 3.88s
80:	learn: 17615.2315032	test: 24934.9710155	best: 24441.7119188 (45)	total: 339ms	remaining: 3.84s
81:	learn: 17552.4342305	test: 24941.9288316	best: 24441.7119188 (45)	total: 339ms	remaining: 3.8s
82:	learn: 17499.6928714	test: 24964.7345310	best: 24441.7119188 (45)	total: 340ms	remaining: 3.76s
83:	learn: 17439.5766954	test: 24999.1898780	best: 24441.7119188 (45)	total: 341ms	remaining: 3.72s
84:	learn: 17394.5293474	test: 25002.9772169	best: 24441.7119188 (45)	total: 342ms	remaining: 3.68s
85:	learn: 17376.4352698	test: 25012.6489728	best: 24441.7119188 (45)	total: 342ms	remaining: 3.64s
86:	learn: 17317.3680700	test: 25014.3206602	best: 24441.7119188 (45)	total: 343ms	remaining: 3.6s
87:	learn: 17232.4100718	test: 25047.6203557	best: 24441.7119188 (45)	total: 344ms	remaining: 3.56s
88:	learn: 17211.2517852	test: 25063.0258905	best: 24441.7119188 (45)	total: 345ms	remaining: 3.53s
89:	learn: 17174.0555833	test: 25075.4337048	best: 24441.7119188 (45)	total: 348ms	remaining: 3.52s
90:	learn: 17129.9997008	test: 25077.2802045	best: 24441.7119188 (45)	total: 356ms	remaining: 3.56s
91:	learn: 17101.1024074	test: 25095.9439745	best: 24441.7119188 (45)	total: 365ms	remaining: 3.6s
92:	learn: 17054.1202207	test: 25137.6369455	best: 24441.7119188 (45)	total: 374ms	remaining: 3.65s
93:	learn: 16977.3444006	test: 25133.3870957	best: 24441.7119188 (45)	total: 382ms	remaining: 3.68s
94:	learn: 16928.0416402	test: 25153.4180759	best: 24441.7119188 (45)	total: 390ms	remaining: 3.71s
95:	learn: 16882.7389006	test: 25193.9779245	best: 24441.7119188 (45)	total: 398ms	remaining: 3.75s
96:	learn: 16834.0755262	test: 25216.6221041	best: 24441.7119188 (45)	total: 405ms	remaining: 3.77s
97:	learn: 16780.1266898	test: 25226.4475961	best: 24441.7119188 (45)	total: 412ms	remaining: 3.79s
98:	learn: 16744.8002852	test: 25186.2440544	best: 24441.7119188 (45)	total: 420ms	remaining: 3.82s
99:	learn: 16696.1354425	test: 25187.3624748	best: 24441.7119188 (45)	total: 427ms	remaining: 3.84s
100:	learn: 16662.3542403	test: 25213.6140849	best: 24441.7119188 (45)	total: 433ms	remaining: 3.85s
101:	learn: 16642.8412245	test: 25215.7979724	best: 24441.7119188 (45)	total: 440ms	remaining: 3.87s
102:	learn: 16596.9396354	test: 25225.5536654	best: 24441.7119188 (45)	total: 446ms	remaining: 3.89s
103:	learn: 16544.2627293	test: 25247.4111598	best: 24441.7119188 (45)	total: 453ms	remaining: 3.9s
104:	learn: 16494.8673666	test: 25255.7009222	best: 24441.7119188 (45)	total: 458ms	remaining: 3.9s
105:	learn: 16459.5774180	test: 25259.4634728	best: 24441.7119188 (45)	total: 461ms	remaining: 3.88s
106:	learn: 16393.1493279	test: 25253.9871298	best: 24441.7119188 (45)	total: 465ms	remaining: 3.88s
107:	learn: 16371.2558229	test: 25263.5884632	best: 24441.7119188 (45)	total: 472ms	remaining: 3.9s
108:	learn: 16355.2274735	test: 25270.5394583	best: 24441.7119188 (45)	total: 477ms	remaining: 3.9s
109:	learn: 16299.5898773	test: 25296.2644174	best: 24441.7119188 (45)	total: 483ms	remaining: 3.91s
110:	learn: 16237.7716566	test: 25295.0368660	best: 24441.7119188 (45)	total: 488ms	remaining: 3.91s
111:	learn: 16215.2975611	test: 25298.4618169	best: 24441.7119188 (45)	total: 494ms	remaining: 3.91s
112:	learn: 16175.3968866	test: 25303.4062491	best: 24441.7119188 (45)	total: 500ms	remaining: 3.93s
113:	learn: 16154.7940775	test: 25299.8779601	best: 24441.7119188 (45)	total: 507ms	remaining: 3.94s
114:	learn: 16113.6044821	test: 25334.2657920	best: 24441.7119188 (45)	total: 514ms	remaining: 3.95s
115:	learn: 16084.5298101	test: 25348.2040042	best: 24441.7119188 (45)	total: 519ms	remaining: 3.95s
116:	learn: 16073.4204687	test: 25352.9599779	best: 24441.7119188 (45)	total: 523ms	remaining: 3.94s
117:	learn: 16049.7985108	test: 25364.8731861	best: 24441.7119188 (45)	total: 528ms	remaining: 3.94s
118:	learn: 16031.9238889	test: 25367.1335926	best: 24441.7119188 (45)	total: 529ms	remaining: 3.92s
119:	learn: 15986.6053217	test: 25396.9366596	best: 24441.7119188 (45)	total: 529ms	remaining: 3.88s
120:	learn: 15980.7490280	test: 25399.7713394	best: 24441.7119188 (45)	total: 530ms	remaining: 3.85s
121:	learn: 15935.5324861	test: 25397.7569780	best: 24441.7119188 (45)	total: 530ms	remaining: 3.81s
122:	learn: 15909.0859884	test: 25411.6561491	best: 24441.7119188 (45)	total: 531ms	remaining: 3.78s
123:	learn: 15869.6517593	test: 25446.2286789	best: 24441.7119188 (45)	total: 531ms	remaining: 3.75s
124:	learn: 15841.1191691	test: 25447.1973734	best: 24441.7119188 (45)	total: 532ms	remaining: 3.72s
125:	learn: 15808.2462690	test: 25477.9391483	best: 24441.7119188 (45)	total: 532ms	remaining: 3.69s
126:	learn: 15753.0210453	test: 25476.0923531	best: 24441.7119188 (45)	total: 533ms	remaining: 3.66s
127:	learn: 15735.7218260	test: 25472.0574860	best: 24441.7119188 (45)	total: 533ms	remaining: 3.63s
128:	learn: 15689.3837781	test: 25491.2049354	best: 24441.7119188 (45)	total: 534ms	remaining: 3.6s
129:	learn: 15674.9519206	test: 25491.9433294	best: 24441.7119188 (45)	total: 534ms	remaining: 3.57s
130:	learn: 15651.7326716	test: 25495.6281909	best: 24441.7119188 (45)	total: 535ms	remaining: 3.55s
131:	learn: 15606.2250954	test: 25492.0384016	best: 24441.7119188 (45)	total: 535ms	remaining: 3.52s
132:	learn: 15572.1948130	test: 25521.4905318	best: 24441.7119188 (45)	total: 536ms	remaining: 3.49s
133:	learn: 15533.8709080	test: 25549.0437552	best: 24441.7119188 (45)	total: 536ms	remaining: 3.46s
134:	learn: 15494.6966526	test: 25543.6892523	best: 24441.7119188 (45)	total: 537ms	remaining: 3.44s
135:	learn: 15440.4375619	test: 25530.2516029	best: 24441.7119188 (45)	total: 537ms	remaining: 3.41s
136:	learn: 15414.3368740	test: 25543.0841508	best: 24441.7119188 (45)	total: 537ms	remaining: 3.38s
137:	learn: 15389.2788233	test: 25553.9047669	best: 24441.7119188 (45)	total: 538ms	remaining: 3.36s
138:	learn: 15359.7623884	test: 25555.5191227	best: 24441.7119188 (45)	total: 538ms	remaining: 3.33s
139:	learn: 15326.0795571	test: 25585.8760452	best: 24441.7119188 (45)	total: 539ms	remaining: 3.31s
140:	learn: 15304.2237055	test: 25586.3407641	best: 24441.7119188 (45)	total: 539ms	remaining: 3.29s
141:	learn: 15285.8460803	test: 25582.7500029	best: 24441.7119188 (45)	total: 540ms	remaining: 3.26s
142:	learn: 15227.8648342	test: 25584.1995506	best: 24441.7119188 (45)	total: 540ms	remaining: 3.24s
143:	learn: 15187.0868403	test: 25579.8844198	best: 24441.7119188 (45)	total: 541ms	remaining: 3.21s
144:	learn: 15176.1215717	test: 25578.6799375	best: 24441.7119188 (45)	total: 541ms	remaining: 3.19s
145:	learn: 15165.4083808	test: 25587.7802647	best: 24441.7119188 (45)	total: 542ms	remaining: 3.17s
146:	learn: 15151.9071722	test: 25605.3433776	best: 24441.7119188 (45)	total: 542ms	remaining: 3.15s
147:	learn: 15141.0334072	test: 25601.1278143	best: 24441.7119188 (45)	total: 548ms	remaining: 3.16s
148:	learn: 15118.5309657	test: 25598.8678217	best: 24441.7119188 (45)	total: 555ms	remaining: 3.17s
149:	learn: 15102.7169038	test: 25601.9835707	best: 24441.7119188 (45)	total: 562ms	remaining: 3.19s
150:	learn: 15075.6694094	test: 25600.9017022	best: 24441.7119188 (45)	total: 570ms	remaining: 3.2s
151:	learn: 15047.3363647	test: 25597.7161651	best: 24441.7119188 (45)	total: 577ms	remaining: 3.22s
152:	learn: 15034.6979206	test: 25601.7700408	best: 24441.7119188 (45)	total: 583ms	remaining: 3.23s
153:	learn: 15022.0082607	test: 25602.0085869	best: 24441.7119188 (45)	total: 589ms	remaining: 3.23s
154:	learn: 15004.7722854	test: 25616.5761440	best: 24441.7119188 (45)	total: 595ms	remaining: 3.24s
155:	learn: 14972.3457511	test: 25634.2977213	best: 24441.7119188 (45)	total: 600ms	remaining: 3.25s
156:	learn: 14958.3336596	test: 25635.3929638	best: 24441.7119188 (45)	total: 606ms	remaining: 3.25s
157:	learn: 14944.9543980	test: 25634.2765777	best: 24441.7119188 (45)	total: 614ms	remaining: 3.27s
158:	learn: 14921.0794468	test: 25631.2308561	best: 24441.7119188 (45)	total: 620ms	remaining: 3.28s
159:	learn: 14911.7204414	test: 25630.7914616	best: 24441.7119188 (45)	total: 626ms	remaining: 3.29s
160:	learn: 14880.8652557	test: 25637.8893164	best: 24441.7119188 (45)	total: 632ms	remaining: 3.3s
161:	learn: 14837.6141482	test: 25647.2181225	best: 24441.7119188 (45)	total: 640ms	remaining: 3.31s
162:	learn: 14811.5759883	test: 25673.5988381	best: 24441.7119188 (45)	total: 647ms	remaining: 3.32s
163:	learn: 14774.1235122	test: 25669.4859576	best: 24441.7119188 (45)	total: 655ms	remaining: 3.34s
164:	learn: 14765.8024031	test: 25669.0297284	best: 24441.7119188 (45)	total: 661ms	remaining: 3.35s
165:	learn: 14752.4357939	test: 25668.6843682	best: 24441.7119188 (45)	total: 668ms	remaining: 3.35s
166:	learn: 14709.7676653	test: 25686.0209183	best: 24441.7119188 (45)	total: 675ms	remaining: 3.37s
167:	learn: 14688.6333130	test: 25694.5230429	best: 24441.7119188 (45)	total: 682ms	remaining: 3.38s
168:	learn: 14677.2962300	test: 25688.5066321	best: 24441.7119188 (45)	total: 688ms	remaining: 3.38s
169:	learn: 14632.1645443	test: 25684.2968361	best: 24441.7119188 (45)	total: 695ms	remaining: 3.39s
170:	learn: 14582.6442450	test: 25670.1349689	best: 24441.7119188 (45)	total: 702ms	remaining: 3.4s
171:	learn: 14575.4680631	test: 25670.5594580	best: 24441.7119188 (45)	total: 709ms	remaining: 3.41s
172:	learn: 14565.7437279	test: 25678.2754978	best: 24441.7119188 (45)	total: 714ms	remaining: 3.41s
173:	learn: 14554.5830573	test: 25684.3809726	best: 24441.7119188 (45)	total: 719ms	remaining: 3.41s
174:	learn: 14544.0749729	test: 25685.9668922	best: 24441.7119188 (45)	total: 725ms	remaining: 3.42s
175:	learn: 14470.7763672	test: 25678.4461330	best: 24441.7119188 (45)	total: 731ms	remaining: 3.42s
176:	learn: 14457.1235662	test: 25678.3410415	best: 24441.7119188 (45)	total: 737ms	remaining: 3.43s
177:	learn: 14435.7894736	test: 25674.5333649	best: 24441.7119188 (45)	total: 738ms	remaining: 3.41s
178:	learn: 14423.2793246	test: 25673.9970718	best: 24441.7119188 (45)	total: 739ms	remaining: 3.39s
179:	learn: 14410.0366204	test: 25673.0172682	best: 24441.7119188 (45)	total: 739ms	remaining: 3.37s
180:	learn: 14380.5569493	test: 25676.5141637	best: 24441.7119188 (45)	total: 740ms	remaining: 3.35s
181:	learn: 14343.5189528	test: 25681.7844025	best: 24441.7119188 (45)	total: 740ms	remaining: 3.33s
182:	learn: 14329.8749064	test: 25685.6376216	best: 24441.7119188 (45)	total: 741ms	remaining: 3.31s
183:	learn: 14321.1049573	test: 25686.0708915	best: 24441.7119188 (45)	total: 741ms	remaining: 3.29s
184:	learn: 14312.2528880	test: 25687.3584889	best: 24441.7119188 (45)	total: 741ms	remaining: 3.27s
185:	learn: 14295.5575532	test: 25691.5397313	best: 24441.7119188 (45)	total: 742ms	remaining: 3.25s
186:	learn: 14270.1184672	test: 25714.6433719	best: 24441.7119188 (45)	total: 742ms	remaining: 3.23s
187:	learn: 14261.3172620	test: 25712.2294879	best: 24441.7119188 (45)	total: 743ms	remaining: 3.21s
188:	learn: 14253.2952645	test: 25712.5561553	best: 24441.7119188 (45)	total: 743ms	remaining: 3.19s
189:	learn: 14244.5524646	test: 25712.4988210	best: 24441.7119188 (45)	total: 744ms	remaining: 3.17s
190:	learn: 14234.1643305	test: 25713.5243315	best: 24441.7119188 (45)	total: 744ms	remaining: 3.15s
191:	learn: 14226.6351553	test: 25708.7929022	best: 24441.7119188 (45)	total: 745ms	remaining: 3.13s
192:	learn: 14219.0282574	test: 25708.4956932	best: 24441.7119188 (45)	total: 745ms	remaining: 3.12s
193:	learn: 14186.4415081	test: 25703.8134011	best: 24441.7119188 (45)	total: 746ms	remaining: 3.1s
194:	learn: 14178.7358468	test: 25703.8555782	best: 24441.7119188 (45)	total: 746ms	remaining: 3.08s
195:	learn: 14170.5569379	test: 25703.9663518	best: 24441.7119188 (45)	total: 747ms	remaining: 3.06s
196:	learn: 14161.1161282	test: 25702.9095701	best: 24441.7119188 (45)	total: 747ms	remaining: 3.04s
197:	learn: 14140.8740836	test: 25701.0732089	best: 24441.7119188 (45)	total: 748ms	remaining: 3.03s
198:	learn: 14133.4463353	test: 25703.2892977	best: 24441.7119188 (45)	total: 748ms	remaining: 3.01s

We verify the fit of the model using cross validation.

In [10]:
pd.DataFrame(result['cv_results']).loc[19]

iterations            19.000000
test-RMSE-mean     26904.300910
test-RMSE-std       2723.628305
train-RMSE-mean    26167.676456
train-RMSE-std      1026.770901
Name: 19, dtype: float64

The final parameters chosen.

In [11]:
result['params']

{'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 7}

We apply the `catboost` regressor and calulate the SHAP values and residuals.

In [12]:
explainer = shap.TreeExplainer(mod, X)
shap_values = explainer.shap_values(X)

In [13]:
resid = y.to_numpy() - mod.predict(X)

We test if the normality assumption is valid for the SHAP values and residuals.

In [14]:
print(f"SHAP values: {multivariate_normality(shap_values).pval:.4f}")
print(f"Residuals: {stats.shapiro(resid.reshape(-1)).pvalue:.4f}")

SHAP values: 0.0000
Residuals: 0.0000

They reject the test for normality.

In [15]:
iom_cat = InfluentialOutlierMetric(shap_values, resid,
                                    6, 2, 6, 
                                    1, 1, 2, 
                                    lambdas=np.concatenate([[0], np.exp(np.linspace(-5, 5, 50))]),
                                    lambdas_resid=np.concatenate([[0], np.exp(np.linspace(-5, 5, 50))]),
                                    epoch=500, epoch_resid=500)

In [16]:
# Tune for lambda
iom_cat.find_best_lambda(alpha=0.05)
iom_cat.find_best_lambda_resid(alpha=0.05)

# Compute thresholds
thresholds = iom_cat.find_threshold(alpha=[0.05, 0.01])

# Compute IOM
IOM_cat = iom_cat.IOM()

Finding λ for SHAP values
Henze–Zirkler p-value = 0.0000
λ=0.0000

Normalizing flow:   9%|▉         | 44/500 [00:06<01:03,  7.22it/s]

Normalizing flow: 100%|██████████| 500/500 [01:02<00:00,  7.98it/s]

p=0.3450
---
λ=0.0067

Normalizing flow: 100%|██████████| 500/500 [00:56<00:00,  8.87it/s]

p=0.2111
---
λ=0.0083

Normalizing flow: 100%|██████████| 500/500 [01:04<00:00,  7.81it/s]

p=0.2223
---
λ=0.0101

Normalizing flow: 100%|██████████| 500/500 [00:55<00:00,  8.93it/s]

p=0.2513
---
λ=0.0124

Normalizing flow: 100%|██████████| 500/500 [00:57<00:00,  8.68it/s]

p=0.2225
---
λ=0.0152

Normalizing flow: 100%|██████████| 500/500 [00:53<00:00,  9.32it/s]

p=0.1532
---
λ=0.0187

Normalizing flow: 100%|██████████| 500/500 [00:54<00:00,  9.23it/s]

p=0.1503
---
λ=0.0229

Normalizing flow: 100%|██████████| 500/500 [00:58<00:00,  8.50it/s]

p=0.1141
---
λ=0.0281

Normalizing flow: 100%|██████████| 500/500 [00:58<00:00,  8.54it/s]

p=0.1100
---
λ=0.0345

Normalizing flow: 100%|██████████| 500/500 [01:08<00:00,  7.35it/s]

p=0.0257
---
Selected λ=0.0281, p=0.1100
Done!
Finding λ for residuals
Shapiro p-value = 0.0000
λ=0.0000

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 65.78it/s]

p=0.1045
---
λ=0.0067

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 68.19it/s]

p=0.1248
---
λ=0.0083

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 68.34it/s]

p=0.1194
---
λ=0.0101

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 67.66it/s]

p=0.1203
---
λ=0.0124

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 67.55it/s]

p=0.1202
---
λ=0.0152

Normalizing flow: 100%|██████████| 500/500 [00:10<00:00, 46.68it/s]

p=0.1171
---
λ=0.0187

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 64.82it/s]

p=0.1131
---
λ=0.0229

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 68.38it/s]

p=0.1095
---
λ=0.0281

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 67.97it/s]

p=0.1066
---
λ=0.0345

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 65.97it/s]

p=0.0977
---
λ=0.0423

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 66.20it/s]

p=0.0922
---
λ=0.0519

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 68.87it/s]

p=0.0864
---
λ=0.0636

Normalizing flow: 100%|██████████| 500/500 [00:06<00:00, 72.31it/s]

p=0.0783
---
λ=0.0780

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 64.99it/s]

p=0.0712
---
λ=0.0957

Normalizing flow: 100%|██████████| 500/500 [00:08<00:00, 61.56it/s]

p=0.0642
---
λ=0.1173

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 68.79it/s]

p=0.0556
---
λ=0.1439

Normalizing flow: 100%|██████████| 500/500 [00:07<00:00, 67.65it/s]

p=0.0444
---
Selected λ=0.1173, p=0.0556
Done!
Threshold at 0.05: 16.9168
Threshold at 0.01: 35.8830

c:\Users\jonc\OneDrive - Bank of Canada\jonc\PhD\main_iom.py:312: IntegrationWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is
  the best which can be obtained.
  val, _ = quad(chi_prod, i, np.inf, args=(m1, m2))

Put it all together.

In [17]:
X_df = pd.DataFrame(X, index=X.index, columns=X.columns)
X_df[["Final consumption expenditure (current US$B)", 
            "Gross capital formation (current US$B)",
            "Gross savings (current US$B)"]] = X_df[["Final consumption expenditure (current US$)", 
                                                          "Gross capital formation (current US$)",	
                                                          "Gross savings (current US$)"]]*1e-9

X_df = X_df.drop(columns=["Final consumption expenditure (current US$)", 
                                "Gross capital formation (current US$)",	
                                "Gross savings (current US$)"])

In [18]:
iom_cat.IOM_.index = X.index
X_df["Outlier"] = np.where(iom_cat.IOM_ > iom_cat.i_star[1], "Influential outlier", "Inlier")

In [19]:
Final = pd.concat([X_df,
                   pd.Series(y, name="GDP per capita (current US$)"),
                   pd.Series(iom_cat.chi_z.reshape(-1), name='SHAP leverage (transformed)', index=X.index),
                   pd.Series(iom_cat.chi_resid.reshape(-1), name='Residual squared (transformed)', index=X.index),
                   iom_cat.IOM_],
            axis=1)

In [20]:
round(Final[Final["Outlier"]=="Influential outlier"], 2).drop(columns=["Outlier"]).sort_values("IOM", ascending=False).round(2)

,Population growth (annual %),Final consumption expenditure (current US$B),Gross capital formation (current US$B),Gross savings (current US$B),GDP per capita (current US$),SHAP leverage (transformed),Residual squared (transformed),IOM
Luxembourg,2.02,39.36,14.49,14.91,125006.02,16.36,15.23,249.23
Iceland,2.51,21.80,7.01,6.42,75314.09,6.19,8.98,55.58

In [21]:
iom_cat.summary()

               Parameter      Value
             Samples (n) 150.000000
            Features (p)   4.000000
       Flow depth (SHAP)   6.000000
     Hidden units (SHAP)   6.000000
           Layers (SHAP)   2.000000
  Flow depth (Residuals)   1.000000
Hidden units (Residuals)   2.000000
      Layers (Residuals)   1.000000
          Final λ (SHAP)   0.028116
            Shap p-value   0.109956
     Final λ (Residuals)   0.117319
        Residual p-value   0.055648
      Threshold (α=0.05)  16.916796
      Threshold (α=0.01)  35.883027

                   Parameter       Value
0                Samples (n)  150.000000
1               Features (p)    4.000000
2          Flow depth (SHAP)    6.000000
3        Hidden units (SHAP)    6.000000
4              Layers (SHAP)    2.000000
5     Flow depth (Residuals)    1.000000
6   Hidden units (Residuals)    2.000000
7         Layers (Residuals)    1.000000
8             Final λ (SHAP)    0.028116
9               Shap p-value    0.109956
10       Final λ (Residuals)    0.117319
11          Residual p-value    0.055648
12        Threshold (α=0.05)   16.916796
13        Threshold (α=0.01)   35.883027